[package]
name = "antimono"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4-core-raw = { path = "sel4-core-raw" }
log = "0.4"
anti-frame = { path = "crates/anti-frame" }
# [dependencies.aster-frame]
# path = "../asterinas/framework/aster-frame"

[workspace]
resolver = "2"
members = [
  "crates/align-ext",
  "crates/anti-frame",
  "crates/anti-main",
  "crates/id-alloc",
  "crates/int-to-c-enum",
  "sel4-core-raw",
  # "sel4",
]
exclude = ["target/osdk/base"]
