[package]
name = "antimono"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4 = { path = "./sel4" }
log = "0.4"

[dependencies.aster-frame]
path = "../asterinas/framework/aster-frame"

[workspace]
resolver = "2"
members = [
  "crates/align-ext",
  "crates/anti-frame",
  "crates/anti-main",
  # "sel4-core-raw",
  # "sel4",
]
exclude = ["target/osdk/base"]
