[package]
name = "aster-antimono"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4-core-raw = {path = "./sel4-core-raw"}


[dependencies.aster-frame]
path = "../asterinas/framework/aster-frame"

[dependencies.ktest]
path = "../asterinas/framework/libs/ktest"

[workspace]
resolver = "2"
members = ["am-object","sel4-core-raw", "sel4"]
exclude = ["target/osdk/base"]
