sel4_build_path := "../../proj306-microkernel-test/emberTest/build"
obj-name := "emberTest-image-x86_64-pc99"

run: 
  cargo osdk run

build: 
  cargo osdk build

asm-kernel:
  rust-objdump -d target/x86_64-unknown-none/debug/antimono-osdk-bin > asm/kernel.asm

asm-user:
  objdump -d images/root_task > asm/user.asm

debug: 
  cargo osdk run --enable-gdb --gdb-server-addr 127.0.0.1:1234

copy-image:
  cd {{sel4_build_path}} && ninja
  cp {{sel4_build_path}}/images/{{obj-name}} images/root_task
  