sel4_build_path := "../../proj306-microkernel-test/emberTest/build"
obj-name := "emberTest-image-x86_64-pc99"

kernel_path := "target/x86_64-unknown-none/debug/kernel"



run: 
  cargo osdk run --target-arch x86_64

ktest:
    cd ember && cargo osdk test --target-arch x86_64

build: 
  cargo osdk build --target-arch x86_64

asm-kernel:
  rust-objdump -d target/x86_64-unknown-none/debug/antimono-osdk-bin > asm/kernel.asm

asm-user:
  objdump -d images/root_task > asm/user.asm

debug: 
  cargo osdk run --enable-gdb --gdb-server-addr 127.0.0.1:1234

copy-image:
  cd {{sel4_build_path}} && ninja
  cp {{sel4_build_path}}/images/{{obj-name}} images/root_task
  