initramfs = "images/capabilities-image-x86_64-pc99"

[boot]
ovmf = "../OVMF"
protocol = "multiboot2"


[qemu]
machine = "q35"
args = [
    "--no-reboot",
    "-m 2G",
    "-nographic",
    "-serial chardev:mux",
    "-monitor chardev:mux",
    "-chardev stdio,id=mux,mux=on,signal=off",
    "-display none",
    "-device isa-debug-exit,iobase=0xf4,iosize=0x04",
]
