[package]
name = "csel4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sel4-core-raw = { path = "../sel4-core-raw" }


[build-dependencies]
cbindgen = "0.26"
